academic_analysis_task:
  description: >
    Analyze the student's profile with academic percentage of {academic_percentage}%, 
    school name "{school_name}", and age {age} years. Evaluate their current academic 
    standing, identify strengths and weaknesses, and assess their readiness for JEE preparation.
    Consider factors like:
    - Board type and school reputation
    - Academic performance relative to JEE requirements
    - Age-appropriate preparation timeline
    - Current knowledge gaps
    Make sure to provide a realistic assessment for the current year {current_year}.
  expected_output: >
    A detailed academic analysis report covering:
    - Current academic standing assessment
    - Strengths and areas for improvement
    - JEE readiness evaluation
    - Recommended preparation timeline based on age
    - Key focus areas for improvement
  agent: academic_analyzer

study_planning_task:
  description: >
    Based on the academic analysis, create a comprehensive and personalized study roadmap 
    for JEE preparation. The student has {academic_percentage}% academic performance, 
    is {age} years old, and studies at "{school_name}". 
    Create a detailed month-by-month study plan that includes:
    - Subject-wise preparation strategy
    - Daily and weekly study schedules
    - Milestone targets and mock test schedules
    - Revision strategies
    - Time management techniques
    Consider the current year is {current_year} and plan accordingly for upcoming JEE cycles.
  expected_output: >
    A comprehensive study roadmap including:
    - Phase-wise preparation plan
    - Subject-wise study schedule
    - Monthly targets and milestones
    - Daily routine recommendations
    - Mock test and assessment schedule
    - Revision and practice strategies
  agent: study_planner

resource_recommendation_task:
  description: >
    Recommend the best study materials, resources, and coaching options based on the 
    student profile (Academic: {academic_percentage}%, Age: {age}, School: "{school_name}").
    Provide specific recommendations for:
    - Books and study materials for each subject
    - Online platforms and apps
    - Coaching institute suggestions (if needed)
    - Mock test series
    - Previous year papers and practice resources
    Consider budget-friendly options and premium resources.
  expected_output: >
    A detailed resource recommendation guide including:
    - Subject-wise book recommendations
    - Online learning platforms and tools
    - Coaching options (online/offline)
    - Mock test series and assessment tools
    - Free and paid resource options
    - Study apps and digital tools
  agent: resource_advisor

final_roadmap_compilation:
  description: >
    Compile all the analysis, study plans, and resource recommendations into a 
    comprehensive JEE preparation roadmap. Ensure the roadmap is practical, 
    actionable, and tailored to the student's profile. Include motivational 
    elements and success tips.
  expected_output: >
    A complete JEE preparation roadmap document formatted as markdown without '```' containing:
    - Executive summary of the student's profile
    - Detailed preparation strategy
    - Month-wise study plan
    - Resource recommendations
    - Success tips and motivation
    - Timeline to JEE exam
    - Contingency plans and alternatives
  agent: study_planner